version: 0.1
resource_usage:
  google_storage_bucket.tbd-staging-bucket:
    storage_gb: 100                   # Total size of bucket in GB.
    monthly_class_a_operations: 40000 # Monthly number of class A operations (object adds, bucket/object list).
    monthly_class_b_operations: 20000 # Monthly number of class B operations (object gets, retrieve bucket/object metadata).
    monthly_data_retrieval_gb: 1000
    monthly_egress_data_transfer_gb:  # Monthly data transfer from Cloud Storage to the following, in GB:
      same_continent: 550  # Same continent.
      worldwide: 12500     # Worldwide excluding Asia, Australia.
      asia: 1500           # Asia excluding China, but including Hong Kong.
      china: 50            # China excluding Hong Kong.
      australia: 250       # Australia.
  
  # Note: we use Standard mode, so I'm setting only fields relevant for this one.
  google_container_cluster.primary: 
    nodes: 4                          # Node count per zone for the default node pool. Only relevant for Standard mode.
    node_pool[0]:
      nodes: 2                        # Node count per zone for the first node pool. Only relevant for Standard mode.

  google_container_node_pool.primary_preemptible_nodes:
    nodes: 4 # Node count per zone for the node pool
